server:
  port: 8090
spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    OnlineBankingCustomer:
      path: /onlinebanking/customer/**
      url: http://localhost:8086/onlinebanking/customer/**
      serviceId: OnlineBankingCustomer
    OnlineBankingAccounts:
      path: /onlinebanking/account/**
      url: http://localhost:8087/onlinebanking/account/**
      serviceId: OnlineBankingAccounts
    OnlineBankingTransactions:
      path: /onlinebanking/transaction/**
      url: http://localhost:8088/onlinebanking/transaction/**
      serviceId: OnlineBankingTransactions
        